#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_DEL, OSL(4), LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, RSFT_T(KC_J), RCTL_T(KC_K), LALT_T(KC_L), LGUI_T(KC_SCLN), KC_QUOT, TG(3), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_BSPC, KC_ESC, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, CW_TOGG, KC_LGUI, LT(1, KC_TAB), KC_SPC, SC_SENT, LT(2, KC_RALT), LT(3, KC_APP)),
[1] = LAYOUT(TG(1), KC_PSCR, KC_HOME, KC_PGUP, KC_INS, KC_PAUS, KC_ACL0, KC_ACL1, KC_ACL2, KC_MUTE, KC_VOLD, KC_VOLU, KC_TRNS, KC_SCRL, KC_END, KC_PGDN, KC_DEL, CW_TOGG, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_MPRV, KC_MNXT, KC_TRNS, OSM(MOD_LGUI), OSM(MOD_LSFT), OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_MEH), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_MPLY, KC_MSTP, KC_TRNS, LCTL(KC_Z), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), LCTL(KC_Y), KC_TRNS, KC_TRNS, KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, KC_BTN4, KC_BTN5, KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_BTN2, KC_BTN3),
	[2] = LAYOUT(TG(2), KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_TAB, KC_GRV, KC_LT, KC_GT, KC_DQUO, KC_DOT, KC_AMPR, KC_EQL, KC_LBRC, KC_RBRC, KC_RPRN, KC_F12, KC_TRNS, KC_EXLM, KC_MINS, KC_PLUS, KC_EQL, KC_HASH, KC_PIPE, KC_COLN, KC_LPRN, KC_RPRN, KC_QUES, KC_NO, KC_TRNS, KC_CIRC, KC_SLSH, KC_ASTR, KC_BSLS, KC_UNDS, KC_DEL, KC_TRNS, KC_TILD, KC_DLR, KC_LCBR, KC_RCBR, KC_AT, KC_NO, KC_TRNS, TT(3), KC_BSPC, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT(TG(3), RGB_TOG, RGB_MOD, RGB_RMOD, RGB_VAD, RGB_VAI, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSPC, KC_TRNS, BL_TOGG, BL_STEP, BL_ON, BL_UP, BL_DOWN, KC_PAST, KC_7, KC_8, KC_9, KC_PSLS, KC_TRNS, KC_TRNS, KC_LGUI, KC_LSFT, KC_LCTL, KC_LALT, KC_TRNS, KC_MINS, KC_4, KC_5, KC_6, KC_PPLS, KC_TRNS, KC_TRNS, LCTL(KC_Z), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), LCTL(KC_Y), KC_TRNS, KC_TRNS, KC_TRNS, KC_1, KC_2, KC_3, KC_EQL, KC_PENT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DOT, KC_0),
	[4] = LAYOUT(0x7c70, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, 0x7c71, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 0x7c72, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)



const uint16_t PROGMEM jk_esc[] = {RSFT_T(KC_J), RCTL_T(KC_K), COMBO_END};
const uint16_t PROGMEM gk_f12[] = {KC_G, KC_H, COMBO_END};
combo_t key_combos[] = {
    COMBO(jk_esc, KC_ESC),
    COMBO(gk_f12, KC_F12),
};

// Achordeon https://getreuer.info/posts/keyboards/achordion/index.html#add-achordion-to-your-keymap
// https://github.com/getreuer/qmk-keymap

#include "features/achordion.h"

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
  if (!process_achordion(keycode, record)) { return false; }
  // Your macros ...

  return true;
}

void matrix_scan_user(void) {
  achordion_task();
}
