#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define CHORDAL_HOLD
/* #define HOLD_ON_OTHER_KEY_PRESS */
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM_PER_KEY
#define DYNAMIC_KEYMAP_LAYER_COUNT 16
